version: "3.9"
services:
  disk:
    build:
      context: ./disk
    environment:
      - DIR=${DIR:?err}
      - TOTAL_SIZE=${TOTAL_SIZE:?err}
      - EFI_SIZE=${EFI_SIZE:?err}
      - LABEL=${LABEL:?err}
      - UUID=${UUID:?err}
    volumes:
      - ./output:/output
      - ./bootloaders/${BOOTLOADER:?err}/EFI:/EFI