version: "3.9"
services:
  grub:
    build:
      context: ./bootloaders/grub
      args:
        - VMLINUZ=${VMLINUZ:?err}
        - INITRAMFS=${INITRAMFS:?err}
        - KERNEL_PARAMETERS=${KERNEL_PARAMETERS:?err}
        - UUID=${UUID:?err}
    volumes:
      - ./bootloaders/grub/EFI:/EFI